services:
  user-service:
    build:
      context: ../../user_service
    env_file:
      - ../../user_service/.env
    ports:
      - "8081:8081"

  product-service:
    build:
      context: ../../product_service
    env_file:
      - ../../product_service/.env
    ports:
      - "8082:8082"

  cart-service:
    build:
      context: ../../cart_service
    env_file:
      - ../../cart_service/.env
    ports:
      - "8083:8083"

  order-service:
    build:
      context: ../../order_service
    env_file:
      - ../../order_service/.env
    ports:
      - "8084:8084"

  payment-service:
    build:
      context: ../../payment_service
    env_file:
      - ../../payment_service/.env
    ports:
      - "8085:8085"

  # notification-service:
  #   build:
  #     context: ../../notification_service
  #   env_file:
  #     - ../../notification_service/.env
  #   ports:
  #     - "8086:8086"
