events {}

http {

    server {
        listen 80;

        location /users/ {
            proxy_pass http://localhost:8081;
        }

        location /products/ {
            proxy_pass http://localhost:8082;
        }

        location /orders/ {
            proxy_pass http://localhost:8083;
        }

        location /cart/ {
            proxy_pass http://localhost:8084;
        }

        location /payments/ {
            proxy_pass http://localhost:8085;
        }

        location /search/ {
            proxy_pass http://localhost:8086;
        }
    }
}